#############################################################################################
## default bash aliases
## https://github.com/pegasusict/PLAT

export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

alias apt="apt-get -qy"
alias update="apt update && apt dist-upgrade && apt autoremove && apt autoclean"
